# Generated by Django 5.2 on 2025-06-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggypetshop', '0002_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
