# Generated by Django 5.2 on 2025-06-04 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggypetshop', '0006_carrito_itemcarrito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTransbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_order', models.CharField(max_length=40, unique=True)),
                ('session_id', models.CharField(max_length=61)),
                ('amount', models.IntegerField()),
                ('token', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(default='CREATED', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('respuesta_transbank', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden Transbank',
                'verbose_name_plural': 'Órdenes Transbank',
            },
        ),
    ]
